export const options = [
  { value: "Ampthill", label: "Ampthill" },
  { value: "Arlesey", label: "Arlesey" },
  { value: "Bedford", label: "Bedford" },
  { value: "Biggleswade", label: "Biggleswade" },
  { value: "Dunstable", label: "Dunstable" },
  { value: "Flitwick", label: "Flitwick" },
  { value: "Houghton Regis", label: "Houghton Regis" },
  { value: "Kempston", label: "Kempston" },
  { value: "Leighton Buzzard", label: "Leighton Buzzard" },
  { value: "Linslade", label: "Linslade" },
  { value: "Luton", label: "Luton" },
  { value: "Potton", label: "Potton" },
  { value: "Sandy", label: "Sandy" },
  { value: "Shefford", label: "Shefford" },
  { value: "Stotfold", label: "Stotfold" },
  { value: "Wixams", label: "Wixams" },
  { value: "Woburn", label: "Woburn" },
  { value: "Ascot", label: "Ascot" },
  { value: "Bracknell", label: "Bracknell" },
  { value: "Crowthorne", label: "Crowthorne" },
  { value: "Earley", label: "Earley" },
  { value: "Eton", label: "Eton" },
  { value: "Hungerford", label: "Hungerford" },
  { value: "Lambourn", label: "Lambourn" },
  { value: "Maidenhead", label: "Maidenhead" },
  { value: "Newbury", label: "Newbury" },
  { value: "Reading", label: "Reading" },
  { value: "Sandhurst", label: "Sandhurst" },
  { value: "Slough", label: "Slough" },
  { value: "Thatcham", label: "Thatcham" },
  { value: "Windsor", label: "Windsor" },
  { value: "Wokingham", label: "Wokingham" },
  { value: "Woodley", label: "Woodley" },
  { value: "Bristol", label: "Bristol" },
  { value: "Amersham", label: "Amersham" },
  { value: "Aylesbury", label: "Aylesbury" },
  { value: "Beaconsfield", label: "Beaconsfield" },
  { value: "Bletchley", label: "Bletchley" },
  { value: "Buckingham", label: "Buckingham" },
  { value: "Chesham", label: "Chesham" },
  { value: "Fenny Stratford", label: "Fenny Stratford" },
  { value: "High Wycombe", label: "High Wycombe" },
  { value: "Marlow", label: "Marlow" },
  { value: "Milton Keynes", label: "Milton Keynes" },
  { value: "Newport Pagnell", label: "Newport Pagnell" },
  { value: "Olney", label: "Olney" },
  { value: "Princes Risborough", label: "Princes Risborough" },
  { value: "Stony Stratford", label: "Stony Stratford" },
  { value: "Wendover", label: "Wendover" },
  { value: "Winslow", label: "Winslow" },
  { value: "Woburn Sands", label: "Woburn Sands" },
  { value: "Wolverton and Greenleys", label: "Wolverton and Greenleys" },
  { value: "Cambridge", label: "Cambridge" },
  { value: "Chatteris", label: "Chatteris" },
  { value: "Ely", label: "Ely" },
  { value: "Fulbourn", label: "Fulbourn" },
  { value: "Godmanchester", label: "Godmanchester" },
  { value: "Hanley Grange", label: "Hanley Grange" },
  { value: "Huntingdon", label: "Huntingdon" },
  { value: "March", label: "March" },
  { value: "Northstowe", label: "Northstowe" },
  { value: "Peterborough", label: "Peterborough" },
  { value: "Ramsey", label: "Ramsey" },
  { value: "Soham", label: "Soham" },
  { value: "St Ives", label: "St Ives" },
  { value: "St Neots", label: "St Neots" },
  { value: "Whittlesey", label: "Whittlesey" },
  { value: "Wisbech", label: "Wisbech" },
  { value: "Alsager", label: "Alsager" },
  { value: "Birchwood", label: "Birchwood" },
  { value: "Bollington", label: "Bollington" },
  { value: "Chester", label: "Chester" },
  { value: "Congleton", label: "Congleton" },
  { value: "Crewe", label: "Crewe" },
  { value: "Ellesmere Port", label: "Ellesmere Port" },
  { value: "Frodsham", label: "Frodsham" },
  { value: "Knutsford", label: "Knutsford" },
  { value: "Macclesfield", label: "Macclesfield" },
  { value: "Malpas", label: "Malpas" },
  { value: "Middlewich", label: "Middlewich" },
  { value: "Nantwich", label: "Nantwich" },
  { value: "Neston", label: "Neston" },
  { value: "Northwich", label: "Northwich" },
  { value: "Poynton with Worth", label: "Poynton with Worth" },
  { value: "Runcorn", label: "Runcorn" },
  { value: "Sandbach", label: "Sandbach" },
  { value: "Warrington", label: "Warrington" },
  { value: "Widnes", label: "Widnes" },
  { value: "Wilmslow", label: "Wilmslow" },
  { value: "Winsford", label: "Winsford" },
  { value: "Bodmin", label: "Bodmin" },
  { value: "Bude", label: "Bude" },
  { value: "Callington", label: "Callington" },
  { value: "Camborne", label: "Camborne" },
  { value: "Camelford", label: "Camelford" },
  { value: "Charlestown", label: "Charlestown" },
  { value: "Falmouth", label: "Falmouth" },
  { value: "Fowey", label: "Fowey" },
  { value: "Hayle", label: "Hayle" },
  { value: "Helston", label: "Helston" },
  { value: "Launceston", label: "Launceston" },
  { value: "Liskeard", label: "Liskeard" },
  { value: "Looe", label: "Looe" },
  { value: "Lostwithiel", label: "Lostwithiel" },
  { value: "Marazion", label: "Marazion" },
  { value: "Newlyn", label: "Newlyn" },
  { value: "Newquay", label: "Newquay" },
  { value: "Padstow", label: "Padstow" },
  { value: "Par", label: "Par" },
  { value: "Penryn", label: "Penryn" },
  { value: "Penzance", label: "Penzance" },
  { value: "Porthleven", label: "Porthleven" },
  { value: "Redruth", label: "Redruth" },
  { value: "Saltash", label: "Saltash" },
  { value: "St Austell", label: "St Austell" },
  { value: "St Blazey", label: "St Blazey" },
  { value: "St Columb Major", label: "St Columb Major" },
  { value: "St Ives", label: "St Ives" },
  { value: "St Just", label: "St Just" },
  { value: "St Mawes", label: "St Mawes" },
  { value: "Stratton", label: "Stratton" },
  { value: "Torpoint", label: "Torpoint" },
  { value: "Truro", label: "Truro" },
  { value: "Wadebridge", label: "Wadebridge" },
  { value: "Barnard Castle", label: "Barnard Castle" },
  { value: "Billingham", label: "Billingham" },
  { value: "Bishop Auckland", label: "Bishop Auckland" },
  { value: "Chester le Street", label: "Chester le Street" },
  { value: "Consett", label: "Consett" },
  { value: "Crook", label: "Crook" },
  { value: "Darlington", label: "Darlington" },
  { value: "Durham", label: "Durham" },
  { value: "Eaglescliffe", label: "Eaglescliffe" },
  { value: "Eastington", label: "Eastington" },
  { value: "Ferryhill", label: "Ferryhill" },
  { value: "Greater Willington", label: "Greater Willington" },
  { value: "Hartlepool", label: "Hartlepool" },
  { value: "Newton Aycliffe", label: "Newton Aycliffe" },
  { value: "Peterlee", label: "Peterlee" },
  { value: "Seaham", label: "Seaham" },
  { value: "Sedgefield", label: "Sedgefield" },
  { value: "Shildon", label: "Shildon" },
  { value: "Spennymoor", label: "Spennymoor" },
  { value: "Stanhope", label: "Stanhope" },
  { value: "Stanley", label: "Stanley" },
  { value: "Stockton on Tees", label: "Stockton on Tees" },
  { value: "Tow Law", label: "Tow Law" },
  { value: "Willington", label: "Willington" },
  { value: "Wolsingham", label: "Wolsingham" },
  { value: "Alston", label: "Alston" },
  { value: "Ambleside", label: "Ambleside" },
  { value: "Appleby in Westmorland", label: "Appleby in Westmorland" },
  { value: "Aspatria", label: "Aspatria" },
  { value: "Barrow in Furness", label: "Barrow in Furness" },
  { value: "Bowness on Windermere", label: "Bowness on Windermere" },
  { value: "Brampton", label: "Brampton" },
  { value: "Broughton in Furness", label: "Broughton in Furness" },
  { value: "Carlisle", label: "Carlisle" },
  { value: "Cleator Moor", label: "Cleator Moor" },
  { value: "Cockermouth", label: "Cockermouth" },
  { value: "Dalton in Furness", label: "Dalton in Furness" },
  { value: "Egremont", label: "Egremont" },
  { value: "Grange over Sands", label: "Grange over Sands" },
  { value: "Harrington", label: "Harrington" },
  { value: "Kendal", label: "Kendal" },
  { value: "Keswick", label: "Keswick" },
  { value: "Kirkby Lonsdale", label: "Kirkby Lonsdale" },
  { value: "Kirkby Stephen", label: "Kirkby Stephen" },
  { value: "Longtown", label: "Longtown" },
  { value: "Maryport", label: "Maryport" },
  { value: "Millom", label: "Millom" },
  { value: "Milnthorpe", label: "Milnthorpe" },
  { value: "Orgill", label: "Orgill" },
  { value: "Penrith", label: "Penrith" },
  { value: "Sedbergh", label: "Sedbergh" },
  { value: "Silloth", label: "Silloth" },
  { value: "Staveley", label: "Staveley" },
  { value: "Ulverston", label: "Ulverston" },
  { value: "Whitehaven", label: "Whitehaven" },
  { value: "Wigton", label: "Wigton" },
  { value: "Windermere", label: "Windermere" },
  { value: "Workington", label: "Workington" },
  { value: "Alfreton", label: "Alfreton" },
  { value: "Ashbourne", label: "Ashbourne" },
  { value: "Bakewell", label: "Bakewell" },
  { value: "Barrow Hill and Whittington", label: "Barrow Hill and Whittington" },
  { value: "Belper", label: "Belper" },
  { value: "Bolsover", label: "Bolsover" },
  { value: "Buxton", label: "Buxton" },
  { value: "Chapel en le Frith", label: "Chapel en le Frith" },
  { value: "Chesterfield", label: "Chesterfield" },
  { value: "Clay Cross", label: "Clay Cross" },
  { value: "Darley Dale", label: "Darley Dale" },
  { value: "Derby", label: "Derby" },
  { value: "Dronfield", label: "Dronfield" },
  { value: "Dronfield Woodhouse", label: "Dronfield Woodhouse" },
  { value: "Eckington", label: "Eckington" },
  { value: "Fairfield", label: "Fairfield" },
  { value: "Glossop", label: "Glossop" },
  { value: "Hadfield", label: "Hadfield" },
  { value: "Heanor", label: "Heanor" },
  { value: "Ilkeston", label: "Ilkeston" },
  { value: "Killamarsh", label: "Killamarsh" },
  { value: "Langley Mill", label: "Langley Mill" },
  { value: "Long Eaton", label: "Long Eaton" },
  { value: "Matlock", label: "Matlock" },
  { value: "Melbourne", label: "Melbourne" },
  { value: "Netherthorpe", label: "Netherthorpe" },
  { value: "New Mills", label: "New Mills" },
  { value: "Over Woodhouse", label: "Over Woodhouse" },
  { value: "Ripley", label: "Ripley" },
  { value: "Sandiacre", label: "Sandiacre" },
  { value: "Shallcross", label: "Shallcross" },
  { value: "Shirebrook", label: "Shirebrook" },
  { value: "Staveley", label: "Staveley" },
  { value: "Swadlincote", label: "Swadlincote" },
  { value: "Whaley Bridge", label: "Whaley Bridge" },
  { value: "Wirksworth", label: "Wirksworth" },
  { value: "Ashburton", label: "Ashburton" },
  { value: "Axminster", label: "Axminster" },
  { value: "Bampton", label: "Bampton" },
  { value: "Barnstaple", label: "Barnstaple" },
  { value: "Bideford", label: "Bideford" },
  { value: "Bovey Tracey", label: "Bovey Tracey" },
  { value: "Bradninch", label: "Bradninch" },
  { value: "Brixham", label: "Brixham" },
  { value: "Buckfastleigh", label: "Buckfastleigh" },
  { value: "Budleigh Salterton", label: "Budleigh Salterton" },
  { value: "Chagford", label: "Chagford" },
  { value: "Chudleigh", label: "Chudleigh" },
  { value: "Chulmleigh", label: "Chulmleigh" },
  { value: "Colyton", label: "Colyton" },
  { value: "Crediton", label: "Crediton" },
  { value: "Cullompton", label: "Cullompton" },
  { value: "Dartmouth", label: "Dartmouth" },
  { value: "Dawlish", label: "Dawlish" },
  { value: "Exeter", label: "Exeter" },
  { value: "Exmouth", label: "Exmouth" },
  { value: "Great Torrington", label: "Great Torrington" },
  { value: "Hartland", label: "Hartland" },
  { value: "Hatherleigh", label: "Hatherleigh" },
  { value: "Highampton", label: "Highampton" },
  { value: "Holsworthy", label: "Holsworthy" },
  { value: "Honiton", label: "Honiton" },
  { value: "Ilfracombe", label: "Ilfracombe" },
  { value: "Ivybridge", label: "Ivybridge" },
  { value: "Kingsbridge", label: "Kingsbridge" },
  { value: "Kingsteignton", label: "Kingsteignton" },
  { value: "Lynton", label: "Lynton" },
  { value: "Modbury", label: "Modbury" },
  { value: "Moretonhampstead", label: "Moretonhampstead" },
  { value: "Newton Abbot", label: "Newton Abbot" },
  { value: "North Tawton", label: "North Tawton" },
  { value: "Northam", label: "Northam" },
  { value: "Okehampton", label: "Okehampton" },
  { value: "Ottery St Mary", label: "Ottery St Mary" },
  { value: "Paignton", label: "Paignton" },
  { value: "Plymouth", label: "Plymouth" },
  { value: "Princetown", label: "Princetown" },
  { value: "Salcombe", label: "Salcombe" },
  { value: "Seaton", label: "Seaton" },
  { value: "Sherford", label: "Sherford" },
  { value: "Sidmouth", label: "Sidmouth" },
  { value: "South Molton", label: "South Molton" },
  { value: "Tavistock", label: "Tavistock" },
  { value: "Teignmouth", label: "Teignmouth" },
  { value: "Tiverton", label: "Tiverton" },
  { value: "Topsham", label: "Topsham" },
  { value: "Torquay", label: "Torquay" },
  { value: "Totnes", label: "Totnes" },
  { value: "Beaminster", label: "Beaminster" },
  { value: "Blandford Forum", label: "Blandford Forum" },
  { value: "Bournemouth", label: "Bournemouth" },
  { value: "Bridport", label: "Bridport" },
  { value: "Chickerell", label: "Chickerell" },
  { value: "Christchurch", label: "Christchurch" },
  { value: "Dorchester", label: "Dorchester" },
  { value: "Ferndown", label: "Ferndown" },
  { value: "Gillingham", label: "Gillingham" },
  { value: "Highcliffe", label: "Highcliffe" },
  { value: "Lyme Regis", label: "Lyme Regis" },
  { value: "Poole", label: "Poole" },
  { value: "Portland", label: "Portland" },
  { value: "Shaftesbury", label: "Shaftesbury" },
  { value: "Sherborne", label: "Sherborne" },
  { value: "Stalbridge", label: "Stalbridge" },
  { value: "Sturminster Newton", label: "Sturminster Newton" },
  { value: "Swanage", label: "Swanage" },
  { value: "Verwood", label: "Verwood" },
  { value: "Wareham", label: "Wareham" },
  { value: "Weymouth", label: "Weymouth" },
  { value: "Wimborne Minster", label: "Wimborne Minster" },
  { value: "Beverley", label: "Beverley" },
  { value: "Bridlington", label: "Bridlington" },
  { value: "Brough", label: "Brough" },
  { value: "Driffield", label: "Driffield" },
  { value: "Goole", label: "Goole" },
  { value: "Hedon", label: "Hedon" },
  { value: "Hessle", label: "Hessle" },
  { value: "Hornsea", label: "Hornsea" },
  { value: "Howden", label: "Howden" },
  { value: "Market Weighton", label: "Market Weighton" },
  { value: "Pocklington", label: "Pocklington" },
  { value: "Snaith", label: "Snaith" },
  { value: "South Cave", label: "South Cave" },
  { value: "Withernsea", label: "Withernsea" },
  { value: "Battle", label: "Battle" },
  { value: "Bexhill on Sea", label: "Bexhill on Sea" },
  { value: "Brighton", label: "Brighton" },
  { value: "Crowborough", label: "Crowborough" },
  { value: "Eastbourne", label: "Eastbourne" },
  { value: "Hailsham", label: "Hailsham" },
  { value: "Hastings", label: "Hastings" },
  { value: "Heathfield", label: "Heathfield" },
  { value: "Hove", label: "Hove" },
  { value: "Lewes", label: "Lewes" },
  { value: "Newhaven", label: "Newhaven" },
  { value: "Ore Valley", label: "Ore Valley" },
  { value: "Peacehaven", label: "Peacehaven" },
  { value: "Polegate", label: "Polegate" },
  { value: "Rye", label: "Rye" },
  { value: "Seaford", label: "Seaford" },
  { value: "Telscombe", label: "Telscombe" },
  { value: "Uckfield", label: "Uckfield" },
  { value: "Wadhurst", label: "Wadhurst" },
  { value: "Winchelsea", label: "Winchelsea" },
  { value: "Basildon", label: "Basildon" },
  { value: "Billericay", label: "Billericay" },
  { value: "Braintree", label: "Braintree" },
  { value: "Brentwood", label: "Brentwood" },
  { value: "Brightlingsea", label: "Brightlingsea" },
  { value: "Buckhurst Hill", label: "Buckhurst Hill" },
  { value: "Burnham on Crouch", label: "Burnham on Crouch" },
  { value: "Canvey Island", label: "Canvey Island" },
  { value: "Chafford Hundred", label: "Chafford Hundred" },
  { value: "Chelmsford", label: "Chelmsford" },
  { value: "Clackwell", label: "Clackwell" },
  { value: "Clacton on Sea", label: "Clacton on Sea" },
  { value: "Coggeshall", label: "Coggeshall" },
  { value: "Colchester", label: "Colchester" },
  { value: "Corringham", label: "Corringham" },
  { value: "Dovercourt", label: "Dovercourt" },
  { value: "Eastwood", label: "Eastwood" },
  { value: "Epping", label: "Epping" },
  { value: "Frinton on Sea", label: "Frinton on Sea" },
  { value: "Grays", label: "Grays" },
  { value: "Great Dunmow", label: "Great Dunmow" },
  { value: "Hadleigh", label: "Hadleigh" },
  { value: "Halstead", label: "Halstead" },
  { value: "Harlow", label: "Harlow" },
  { value: "Harwich", label: "Harwich" },
  { value: "Heybridge", label: "Heybridge" },
  { value: "Hockley", label: "Hockley" },
  { value: "Holland on Sea", label: "Holland on Sea" },
  { value: "Ingatestone", label: "Ingatestone" },
  { value: "Laindon", label: "Laindon" },
  { value: "Langdon Hills", label: "Langdon Hills" },
  { value: "Leigh on Sea", label: "Leigh on Sea" },
  { value: "Loughton", label: "Loughton" },
  { value: "Maldon", label: "Maldon" },
  { value: "Manningtree", label: "Manningtree" },
  { value: "North Shoebury", label: "North Shoebury" },
  { value: "Ongar", label: "Ongar" },
  { value: "Parkeston", label: "Parkeston" },
  { value: "Pitsea", label: "Pitsea" },
  { value: "Prettlewell", label: "Prettlewell" },
  { value: "Rayleigh", label: "Rayleigh" },
  { value: "Rochford", label: "Rochford" },
  { value: "Romford", label: "Romford" },
  { value: "Saffron Walden", label: "Saffron Walden" },
  { value: "Shoeburyness", label: "Shoeburyness" },
  { value: "South Benfleet", label: "South Benfleet" },
  { value: "South Woodham Ferrers", label: "South Woodham Ferrers" },
  { value: "Southchurch", label: "Southchurch" },
  { value: "Southend on Sea", label: "Southend on Sea" },
  { value: "Southminster", label: "Southminster" },
  { value: "Stanfield le Hope", label: "Stanfield le Hope" },
  { value: "Thaxted", label: "Thaxted" },
  { value: "Thorpe Bay", label: "Thorpe Bay" },
  { value: "Tilbury", label: "Tilbury" },
  { value: "Waltham Abbey", label: "Waltham Abbey" },
  { value: "Walton on the Naze", label: "Walton on the Naze" },
  { value: "West Mersea", label: "West Mersea" },
  { value: "West Thurrock", label: "West Thurrock" },
  { value: "West Tilbury", label: "West Tilbury" },
  { value: "Westcliff on Sea", label: "Westcliff on Sea" },
  { value: "Wickford", label: "Wickford" },
  { value: "Witham", label: "Witham" },
  { value: "Wivenhoe", label: "Wivenhoe" },
  { value: "Berkeley", label: "Berkeley" },
  { value: "Bradley Stoke", label: "Bradley Stoke" },
  { value: "Cheltenham", label: "Cheltenham" },
  { value: "Chipping Campden", label: "Chipping Campden" },
  { value: "Chipping Sodbury", label: "Chipping Sodbury" },
  { value: "Cinderford", label: "Cinderford" },
  { value: "Cirencester", label: "Cirencester" },
  { value: "Coleford", label: "Coleford" },
  { value: "Dursley", label: "Dursley" },
  { value: "Fairford", label: "Fairford" },
  { value: "Filton", label: "Filton" },
  { value: "Gloucester", label: "Gloucester" },
  { value: "Kingswood", label: "Kingswood" },
  { value: "Lechlade", label: "Lechlade" },
  { value: "Lydney", label: "Lydney" },
  { value: "Minchinhampton", label: "Minchinhampton" },
  { value: "Mitcheldean", label: "Mitcheldean" },
  { value: "Moreton in Marsh", label: "Moreton in Marsh" },
  { value: "Nailsworth", label: "Nailsworth" },
  { value: "Newent", label: "Newent" },
  { value: "Northleach", label: "Northleach" },
  { value: "Painswick", label: "Painswick" },
  { value: "Patchway", label: "Patchway" },
  { value: "Stonehouse", label: "Stonehouse" },
  { value: "Stow on the Wold", label: "Stow on the Wold" },
  { value: "Stroud", label: "Stroud" },
  { value: "Tetbury", label: "Tetbury" },
  { value: "Tewkesbury", label: "Tewkesbury" },
  { value: "Thornbury", label: "Thornbury" },
  { value: "Wickwar", label: "Wickwar" },
  { value: "Winchcombe", label: "Winchcombe" },
  { value: "Wotton under Edge", label: "Wotton under Edge" },
  { value: "Yate", label: "Yate" },
  { value: "Acton", label: "Acton" },
  { value: "Barking", label: "Barking" },
  { value: "Barnes", label: "Barnes" },
  { value: "Beckenham", label: "Beckenham" },
  { value: "Bexley", label: "Bexley" },
  { value: "Brentford", label: "Brentford" },
  { value: "Bromley", label: "Bromley" },
  { value: "Chingford", label: "Chingford" },
  { value: "Croydon", label: "Croydon" },
  { value: "Dagenham", label: "Dagenham" },
  { value: "Ealing", label: "Ealing" },
  { value: "East Ham", label: "East Ham" },
  { value: "Edgware", label: "Edgware" },
  { value: "Edmonton", label: "Edmonton" },
  { value: "Enfield", label: "Enfield" },
  { value: "Erith", label: "Erith" },
  { value: "Finchley", label: "Finchley" },
  { value: "Harrow", label: "Harrow" },
  { value: "Hendon", label: "Hendon" },
  { value: "Hornsey", label: "Hornsey" },
  { value: "Ilford", label: "Ilford" },
  { value: "Kingston upon Thames", label: "Kingston upon Thames" },
  { value: "Leyton", label: "Leyton" },
  { value: "Mitcham", label: "Mitcham" },
  { value: "Richmond", label: "Richmond" },
  { value: "Southall", label: "Southall" },
  { value: "Southgate", label: "Southgate" },
  { value: "St Mary Cray", label: "St Mary Cray" },
  { value: "Surbiton", label: "Surbiton" },
  { value: "Tottenham", label: "Tottenham" },
  { value: "Twickenham", label: "Twickenham" },
  { value: "Uxbridge", label: "Uxbridge" },
  { value: "Walthamstow", label: "Walthamstow" },
  { value: "Wembley", label: "Wembley" },
  { value: "West Ham", label: "West Ham" },
  { value: "Willesden", label: "Willesden" },
  { value: "Wimbledon", label: "Wimbledon" },
  { value: "Wood Green", label: "Wood Green" },
  { value: "Altrincham", label: "Altrincham" },
  { value: "Ashton in Makerfield", label: "Ashton in Makerfield" },
  { value: "Ashton under Lyne", label: "Ashton under Lyne" },
  { value: "Atherton", label: "Atherton" },
  { value: "Audenshaw", label: "Audenshaw" },
  { value: "Blackrod", label: "Blackrod" },
  { value: "Bolton", label: "Bolton" },
  { value: "Bury", label: "Bury" },
  { value: "Cadishead", label: "Cadishead" },
  { value: "Chadderton", label: "Chadderton" },
  { value: "Cheadle", label: "Cheadle" },
  { value: "Cheadle Hulme", label: "Cheadle Hulme" },
  { value: "Denton", label: "Denton" },
  { value: "Droylsden", label: "Droylsden" },
  { value: "Dukinfield", label: "Dukinfield" },
  { value: "Eccles", label: "Eccles" },
  { value: "Failsworth", label: "Failsworth" },
  { value: "Farnworth", label: "Farnworth" },
  { value: "Golbourne", label: "Golbourne" },
  { value: "Heywood", label: "Heywood" },
  { value: "Hindley", label: "Hindley" },
  { value: "Horwich", label: "Horwich" },
  { value: "Hyde", label: "Hyde" },
  { value: "Ince in Makerfield", label: "Ince in Makerfield" },
  { value: "Irlam", label: "Irlam" },
  { value: "Kearsley", label: "Kearsley" },
  { value: "Leigh", label: "Leigh" },
  { value: "Littleborough", label: "Littleborough" },
  { value: "Manchester", label: "Manchester" },
  { value: "Middleton", label: "Middleton" },
  { value: "Milnrow", label: "Milnrow" },
  { value: "Mossley", label: "Mossley" },
  { value: "Oldham", label: "Oldham" },
  { value: "Partington", label: "Partington" },
  { value: "Pendlebury", label: "Pendlebury" },
  { value: "Prestwich", label: "Prestwich" },
  { value: "Radcliffe", label: "Radcliffe" },
  { value: "Ramsbottom", label: "Ramsbottom" },
  { value: "Rochdale", label: "Rochdale" },
  { value: "Royton", label: "Royton" },
  { value: "Sale", label: "Sale" },
  { value: "Salford", label: "Salford" },
  { value: "Shaw and Crompton", label: "Shaw and Crompton" },
  { value: "Stalybridge", label: "Stalybridge" },
  { value: "Stockport", label: "Stockport" },
  { value: "Stretford", label: "Stretford" },
  { value: "Swinton", label: "Swinton" },
  { value: "Tottington", label: "Tottington" },
  { value: "Tyldsley", label: "Tyldsley" },
  { value: "Walkden", label: "Walkden" },
  { value: "Westhoughton", label: "Westhoughton" },
  { value: "Whitefield", label: "Whitefield" },
  { value: "Wigan", label: "Wigan" },
  { value: "Worsley", label: "Worsley" },
  { value: "Aldershot", label: "Aldershot" },
  { value: "Alton", label: "Alton" },
  { value: "Andover", label: "Andover" },
  { value: "Basingstoke", label: "Basingstoke" },
  { value: "Bishop's Waltham", label: "Bishop's Waltham" },
  { value: "Blackwater and Hawley", label: "Blackwater and Hawley" },
  { value: "Bordon", label: "Bordon" },
  { value: "Eastleigh", label: "Eastleigh" },
  { value: "Emsworth", label: "Emsworth" },
  { value: "Fareham", label: "Fareham" },
  { value: "Farnborough", label: "Farnborough" },
  { value: "Fleet", label: "Fleet" },
  { value: "Fordingbridge", label: "Fordingbridge" },
  { value: "Gosport", label: "Gosport" },
  { value: "Havant", label: "Havant" },
  { value: "Hedge End", label: "Hedge End" },
  { value: "Hythe", label: "Hythe" },
  { value: "Lee on the Solent", label: "Lee on the Solent" },
  { value: "Lymington", label: "Lymington" },
  { value: "Lyndhurst", label: "Lyndhurst" },
  { value: "New Alresford", label: "New Alresford" },
  { value: "New Milton", label: "New Milton" },
  { value: "North Camp", label: "North Camp" },
  { value: "Petersfield", label: "Petersfield" },
  { value: "Portchester", label: "Portchester" },
  { value: "Portsmouth", label: "Portsmouth" },
  { value: "Ringwood", label: "Ringwood" },
  { value: "Romsey", label: "Romsey" },
  { value: "Southampton", label: "Southampton" },
  { value: "Southsea", label: "Southsea" },
  { value: "Southwick", label: "Southwick" },
  { value: "Tadley", label: "Tadley" },
  { value: "Totton", label: "Totton" },
  { value: "Waterlooville", label: "Waterlooville" },
  { value: "Whitchurch", label: "Whitchurch" },
  { value: "Whitehill", label: "Whitehill" },
  { value: "Wickham", label: "Wickham" },
  { value: "Winchester", label: "Winchester" },
  { value: "Yateley", label: "Yateley" },
  { value: "Bromyard", label: "Bromyard" },
  { value: "Hatfield", label: "Hatfield" },
  { value: "Hereford", label: "Hereford" },
  { value: "Kington", label: "Kington" },
  { value: "Ledbury", label: "Ledbury" },
  { value: "Leominster", label: "Leominster" },
  { value: "Longtown", label: "Longtown" },
  { value: "Ross on Wye", label: "Ross on Wye" },
  { value: "Baldock", label: "Baldock" },
  { value: "Barnet", label: "Barnet" },
  { value: "Berkhamsted", label: "Berkhamsted" },
  { value: "Bishop's Stortford", label: "Bishop's Stortford" },
  { value: "Borehamwood", label: "Borehamwood" },
  { value: "Broxbourne", label: "Broxbourne" },
  { value: "Buntingford", label: "Buntingford" },
  { value: "Bushey", label: "Bushey" },
  { value: "Cheshunt", label: "Cheshunt" },
  { value: "Chorleywood", label: "Chorleywood" },
  { value: "Elstree", label: "Elstree" },
  { value: "Harpenden", label: "Harpenden" },
  { value: "Hatfield", label: "Hatfield" },
  { value: "Hemel Hempstead", label: "Hemel Hempstead" },
  { value: "Hertford", label: "Hertford" },
  { value: "Hitchin", label: "Hitchin" },
  { value: "Hoddesdon", label: "Hoddesdon" },
  { value: "Letchworth", label: "Letchworth" },
  { value: "Potters Bar", label: "Potters Bar" },
  { value: "Rickmansworth", label: "Rickmansworth" },
  { value: "Royston", label: "Royston" },
  { value: "Sawbridgeworth", label: "Sawbridgeworth" },
  { value: "Stevenage", label: "Stevenage" },
  { value: "Tring", label: "Tring" },
  { value: "Waltham Cross", label: "Waltham Cross" },
  { value: "Ware", label: "Ware" },
  { value: "Watford", label: "Watford" },
  { value: "Welwyn Garden City", label: "Welwyn Garden City" },
  { value: "Appley", label: "Appley" },
  { value: "Brading", label: "Brading" },
  { value: "Cowes", label: "Cowes" },
  { value: "East Cowes", label: "East Cowes" },
  { value: "Newport", label: "Newport" },
  { value: "Ryde", label: "Ryde" },
  { value: "Sandown", label: "Sandown" },
  { value: "Shanklin", label: "Shanklin" },
  { value: "Ventnor", label: "Ventnor" },
  { value: "Yarmouth", label: "Yarmouth" },
  { value: "Ashford", label: "Ashford" },
  { value: "Broadstairs", label: "Broadstairs" },
  { value: "Canterbury", label: "Canterbury" },
  { value: "Chatham", label: "Chatham" },
  { value: "Cranbrook", label: "Cranbrook" },
  { value: "Crayford", label: "Crayford" },
  { value: "Dartford", label: "Dartford" },
  { value: "Deal", label: "Deal" },
  { value: "Dover", label: "Dover" },
  { value: "Edenbridge", label: "Edenbridge" },
  { value: "Faversham", label: "Faversham" },
  { value: "Folkestone", label: "Folkestone" },
  { value: "Fordwich", label: "Fordwich" },
  { value: "Gillingham", label: "Gillingham" },
  { value: "Gravesend", label: "Gravesend" },
  { value: "Greenhill", label: "Greenhill" },
  { value: "Herne Bay", label: "Herne Bay" },
  { value: "Hythe", label: "Hythe" },
  { value: "Lydd", label: "Lydd" },
  { value: "Maidstone", label: "Maidstone" },
  { value: "Margate", label: "Margate" },
  { value: "Minster", label: "Minster" },
  { value: "New Romney", label: "New Romney" },
  { value: "Northfleet", label: "Northfleet" },
  { value: "Orpington", label: "Orpington" },
  { value: "Paddock Wood", label: "Paddock Wood" },
  { value: "Queenborough", label: "Queenborough" },
  { value: "Rainham", label: "Rainham" },
  { value: "Ramsgate", label: "Ramsgate" },
  { value: "Rochester", label: "Rochester" },
  { value: "Royal Tunbridge Wells", label: "Royal Tunbridge Wells" },
  { value: "Sandwich", label: "Sandwich" },
  { value: "Sevenoaks", label: "Sevenoaks" },
  { value: "Sheerness", label: "Sheerness" },
  { value: "Sittingbourne", label: "Sittingbourne" },
  { value: "Snodland", label: "Snodland" },
  { value: "Southborough", label: "Southborough" },
  { value: "Strood", label: "Strood" },
  { value: "Swanley", label: "Swanley" },
  { value: "Swanscombe and Greenhithe", label: "Swanscombe and Greenhithe" },
  { value: "Tenterden", label: "Tenterden" },
  { value: "Tonbridge", label: "Tonbridge" },
  { value: "Tunbridge Wells", label: "Tunbridge Wells" },
  { value: "West Malling", label: "West Malling" },
  { value: "Westerham", label: "Westerham" },
  { value: "Westgate on Sea", label: "Westgate on Sea" },
  { value: "Whitstable", label: "Whitstable" },
  { value: "Accrington", label: "Accrington" },
  { value: "Adlington", label: "Adlington" },
  { value: "Bacup", label: "Bacup" },
  { value: "Barnoldswick", label: "Barnoldswick" },
  { value: "Blackburn", label: "Blackburn" },
  { value: "Blackpool", label: "Blackpool" },
  { value: "Brierfield", label: "Brierfield" },
  { value: "Burnley", label: "Burnley" },
  { value: "Carnforth", label: "Carnforth" },
  { value: "Chorley", label: "Chorley" },
  { value: "Clayton le Moors", label: "Clayton le Moors" },
  { value: "Cleveleys", label: "Cleveleys" },
  { value: "Clitheroe", label: "Clitheroe" },
  { value: "Colne", label: "Colne" },
  { value: "Darwen", label: "Darwen" },
  { value: "Failsworth", label: "Failsworth" },
  { value: "Fleetwood", label: "Fleetwood" },
  { value: "Garstang", label: "Garstang" },
  { value: "Great Harwood", label: "Great Harwood" },
  { value: "Haslingden", label: "Haslingden" },
  { value: "Kirkham", label: "Kirkham" },
  { value: "Lancaster", label: "Lancaster" },
  { value: "Leyland", label: "Leyland" },
  { value: "Longridge", label: "Longridge" },
  { value: "Lytham St Annes", label: "Lytham St Annes" },
  { value: "Medlar with Wesham", label: "Medlar with Wesham" },
  { value: "Morecambe", label: "Morecambe" },
  { value: "Nelson", label: "Nelson" },
  { value: "Ormskirk", label: "Ormskirk" },
  { value: "Oswaldtwistle", label: "Oswaldtwistle" },
  { value: "Padiham", label: "Padiham" },
  { value: "Penwortham", label: "Penwortham" },
  { value: "Poulton le Fylde", label: "Poulton le Fylde" },
  { value: "Preesall", label: "Preesall" },
  { value: "Preston", label: "Preston" },
  { value: "Rawtenstall", label: "Rawtenstall" },
  { value: "Skelmersdale", label: "Skelmersdale" },
  { value: "Thornton", label: "Thornton" },
  { value: "Thornton Cleveleys", label: "Thornton Cleveleys" },
  { value: "Wesham", label: "Wesham" },
  { value: "Whitworth", label: "Whitworth" },
  { value: "Ashby de la Zouch", label: "Ashby de la Zouch" },
  { value: "Ashby Woulds", label: "Ashby Woulds" },
  { value: "Braunstone Town", label: "Braunstone Town" },
  { value: "Coalville", label: "Coalville" },
  { value: "Earl Shilton", label: "Earl Shilton" },
  { value: "Hinckley", label: "Hinckley" },
  { value: "Leicester", label: "Leicester" },
  { value: "Loughborough", label: "Loughborough" },
  { value: "Lutterworth", label: "Lutterworth" },
  { value: "Market Bosworth", label: "Market Bosworth" },
  { value: "Market Harborough", label: "Market Harborough" },
  { value: "Melton Mowbray", label: "Melton Mowbray" },
  { value: "Oadby", label: "Oadby" },
  { value: "Shepshed", label: "Shepshed" },
  { value: "Syston", label: "Syston" },
  { value: "Wigston Magna", label: "Wigston Magna" },
  { value: "Alford", label: "Alford" },
  { value: "Barton upon Humber", label: "Barton upon Humber" },
  { value: "Boston", label: "Boston" },
  { value: "Bottesford", label: "Bottesford" },
  { value: "Bourne", label: "Bourne" },
  { value: "Brigg", label: "Brigg" },
  { value: "Broughton", label: "Broughton" },
  { value: "Burgh le Marsh", label: "Burgh le Marsh" },
  { value: "Caistor", label: "Caistor" },
  { value: "Cleethorpes", label: "Cleethorpes" },
  { value: "Coningsby", label: "Coningsby" },
  { value: "Crowland", label: "Crowland" },
  { value: "Crowle", label: "Crowle" },
  { value: "Epworth", label: "Epworth" },
  { value: "Gainsborough", label: "Gainsborough" },
  { value: "Grantham", label: "Grantham" },
  { value: "Grimsby", label: "Grimsby" },
  { value: "Holbeach", label: "Holbeach" },
  { value: "Horncastle", label: "Horncastle" },
  { value: "Immingham", label: "Immingham" },
  { value: "Kirton in Lindsey", label: "Kirton in Lindsey" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Little Coates", label: "Little Coates" },
  { value: "Long Sutton", label: "Long Sutton" },
  { value: "Louth", label: "Louth" },
  { value: "Mablethorpe", label: "Mablethorpe" },
  { value: "Mablethorpe and Sutton", label: "Mablethorpe and Sutton" },
  { value: "Market Deeping", label: "Market Deeping" },
  { value: "Market Rasen", label: "Market Rasen" },
  { value: "North Hykeham", label: "North Hykeham" },
  { value: "Scunthorpe", label: "Scunthorpe" },
  { value: "Skegness", label: "Skegness" },
  { value: "Sleaford", label: "Sleaford" },
  { value: "Spalding", label: "Spalding" },
  { value: "Spilsby", label: "Spilsby" },
  { value: "Stamford", label: "Stamford" },
  { value: "The Deepings", label: "The Deepings" },
  { value: "Wainfleet", label: "Wainfleet" },
  { value: "Winterton", label: "Winterton" },
  { value: "Wragby", label: "Wragby" },
  { value: "Bebington", label: "Bebington" },
  { value: "Birkenhead", label: "Birkenhead" },
  { value: "Bootle", label: "Bootle" },
  { value: "Bromborough", label: "Bromborough" },
  { value: "Crosby", label: "Crosby" },
  { value: "Earlestown", label: "Earlestown" },
  { value: "Formby", label: "Formby" },
  { value: "Halewood", label: "Halewood" },
  { value: "Heswall", label: "Heswall" },
  { value: "Hoylake", label: "Hoylake" },
  { value: "Huyton", label: "Huyton" },
  { value: "Kirkby", label: "Kirkby" },
  { value: "Liverpool", label: "Liverpool" },
  { value: "Maghull", label: "Maghull" },
  { value: "Newton le Willows", label: "Newton le Willows" },
  { value: "Prescot", label: "Prescot" },
  { value: "Rainford", label: "Rainford" },
  { value: "Rainhill", label: "Rainhill" },
  { value: "Southport", label: "Southport" },
  { value: "St Helens", label: "St Helens" },
  { value: "Wallasey", label: "Wallasey" },
  { value: "Whiston", label: "Whiston" },
  { value: "Acle", label: "Acle" },
  { value: "Attleborough", label: "Attleborough" },
  { value: "Aylsham", label: "Aylsham" },
  { value: "Caister on Sea", label: "Caister on Sea" },
  { value: "Cromer", label: "Cromer" },
  { value: "Dereham", label: "Dereham" },
  { value: "Diss", label: "Diss" },
  { value: "Downham Market", label: "Downham Market" },
  { value: "Fakenham", label: "Fakenham" },
  { value: "Gorleston", label: "Gorleston" },
  { value: "Great Yarmouth", label: "Great Yarmouth" },
  { value: "Hingham", label: "Hingham" },
  { value: "Holt", label: "Holt" },
  { value: "Hunstanton", label: "Hunstanton" },
  { value: "King's Lynn", label: "King's Lynn" },
  { value: "Loddon", label: "Loddon" },
  { value: "North Walsham", label: "North Walsham" },
  { value: "Norwich", label: "Norwich" },
  { value: "Rackheath", label: "Rackheath" },
  { value: "Redenhall with Harleston", label: "Redenhall with Harleston" },
  { value: "Reepham", label: "Reepham" },
  { value: "Sheringham", label: "Sheringham" },
  { value: "Stalham", label: "Stalham" },
  { value: "Swaffham", label: "Swaffham" },
  { value: "Thetford", label: "Thetford" },
  { value: "Thorpe St Andrew", label: "Thorpe St Andrew" },
  { value: "Watton", label: "Watton" },
  { value: "Wells next the Sea", label: "Wells next the Sea" },
  { value: "Wroxham", label: "Wroxham" },
  { value: "Wymondham", label: "Wymondham" },
  { value: "Bedale", label: "Bedale" },
  { value: "Bentham", label: "Bentham" },
  { value: "Boroughbridge", label: "Boroughbridge" },
  { value: "Colburn", label: "Colburn" },
  { value: "Easingwold", label: "Easingwold" },
  { value: "Eston", label: "Eston" },
  { value: "Filey", label: "Filey" },
  { value: "Grangetown", label: "Grangetown" },
  { value: "Grassington", label: "Grassington" },
  { value: "Guisborough", label: "Guisborough" },
  { value: "Harrogate", label: "Harrogate" },
  { value: "Hawes", label: "Hawes" },
  { value: "Haxby", label: "Haxby" },
  { value: "Helmsley", label: "Helmsley" },
  { value: "Ingleby Barwick", label: "Ingleby Barwick" },
  { value: "Kirkbymoorside", label: "Kirkbymoorside" },
  { value: "Knaresborough", label: "Knaresborough" },
  { value: "Leyburn", label: "Leyburn" },
  { value: "Loftus", label: "Loftus" },
  { value: "Malton", label: "Malton" },
  { value: "Masham", label: "Masham" },
  { value: "Middleham", label: "Middleham" },
  { value: "Middlesbrough", label: "Middlesbrough" },
  { value: "Northallerton", label: "Northallerton" },
  { value: "Norton on Derwent", label: "Norton on Derwent" },
  { value: "Pateley Bridge", label: "Pateley Bridge" },
  { value: "Pickering", label: "Pickering" },
  { value: "Redcar", label: "Redcar" },
  { value: "Richmond", label: "Richmond" },
  { value: "Ripon", label: "Ripon" },
  { value: "Robin Hood's Bay", label: "Robin Hood's Bay" },
  { value: "Saltburn by the Sea", label: "Saltburn by the Sea" },
  { value: "Scarborough", label: "Scarborough" },
  { value: "Selby", label: "Selby" },
  { value: "Settle", label: "Settle" },
  { value: "Sherburn in Elmet", label: "Sherburn in Elmet" },
  { value: "Skelton in Cleveland", label: "Skelton in Cleveland" },
  { value: "Skipton", label: "Skipton" },
  { value: "Stockton on Tees", label: "Stockton on Tees" },
  { value: "Stokesley", label: "Stokesley" },
  { value: "Tadcaster", label: "Tadcaster" },
  { value: "Thirsk", label: "Thirsk" },
  { value: "Thornaby on Tees", label: "Thornaby on Tees" },
  { value: "Whitby", label: "Whitby" },
  { value: "Yarm", label: "Yarm" },
  { value: "York", label: "York" },
  { value: "Brackley", label: "Brackley" },
  { value: "Burton Latimer", label: "Burton Latimer" },
  { value: "Corby", label: "Corby" },
  { value: "Daventry", label: "Daventry" },
  { value: "Desborough", label: "Desborough" },
  { value: "Higham Ferrers", label: "Higham Ferrers" },
  { value: "Irthlingborough", label: "Irthlingborough" },
  { value: "Kettering", label: "Kettering" },
  { value: "Northampton", label: "Northampton" },
  { value: "Oundle", label: "Oundle" },
  { value: "Raunds", label: "Raunds" },
  { value: "Rothwell", label: "Rothwell" },
  { value: "Rushden", label: "Rushden" },
  { value: "Thrapston", label: "Thrapston" },
  { value: "Towcester", label: "Towcester" },
  { value: "Wellingborough", label: "Wellingborough" },
  { value: "Alnwick", label: "Alnwick" },
  { value: "Amble", label: "Amble" },
  { value: "Ashington", label: "Ashington" },
  { value: "Bedlington", label: "Bedlington" },
  { value: "Berwick upon Tweed", label: "Berwick upon Tweed" },
  { value: "Blyth", label: "Blyth" },
  { value: "Corbridge", label: "Corbridge" },
  { value: "Cramlington", label: "Cramlington" },
  { value: "Haltwhistle", label: "Haltwhistle" },
  { value: "Hexham", label: "Hexham" },
  { value: "Morpeth", label: "Morpeth" },
  { value: "Newbiggin by the Sea", label: "Newbiggin by the Sea" },
  { value: "Ponteland", label: "Ponteland" },
  { value: "Prudhoe", label: "Prudhoe" },
  { value: "Rothbury", label: "Rothbury" },
  { value: "West Bedlington", label: "West Bedlington" },
  { value: "Wooler", label: "Wooler" },
  { value: "Arnold", label: "Arnold" },
  { value: "Beeston", label: "Beeston" },
  { value: "Bingham", label: "Bingham" },
  { value: "Bracebridge", label: "Bracebridge" },
  { value: "Bulwell", label: "Bulwell" },
  { value: "Carlton", label: "Carlton" },
  { value: "Cotgrave", label: "Cotgrave" },
  { value: "East Retford", label: "East Retford" },
  { value: "Eastwood", label: "Eastwood" },
  { value: "Harworth and Bircotes", label: "Harworth and Bircotes" },
  { value: "Hucknall", label: "Hucknall" },
  { value: "Kilton", label: "Kilton" },
  { value: "Kimberley", label: "Kimberley" },
  { value: "Kirkby in Ashfield", label: "Kirkby in Ashfield" },
  { value: "Mansfield", label: "Mansfield" },
  { value: "Netherfield", label: "Netherfield" },
  { value: "Newark on Trent", label: "Newark on Trent" },
  { value: "Nottingham", label: "Nottingham" },
  { value: "Ollerton", label: "Ollerton" },
  { value: "Ollerton and Boughton", label: "Ollerton and Boughton" },
  { value: "Retford", label: "Retford" },
  { value: "Southwell", label: "Southwell" },
  { value: "Stapleford", label: "Stapleford" },
  { value: "Sutton in Ashfield", label: "Sutton in Ashfield" },
  { value: "Warsop", label: "Warsop" },
  { value: "West Bridgefield", label: "West Bridgefield" },
  { value: "Worksop", label: "Worksop" },
  { value: "Abingdon", label: "Abingdon" },
  { value: "Banbury", label: "Banbury" },
  { value: "Bicester", label: "Bicester" },
  { value: "Burford", label: "Burford" },
  { value: "Carterton", label: "Carterton" },
  { value: "Charlbury", label: "Charlbury" },
  { value: "Chipping Norton", label: "Chipping Norton" },
  { value: "Didcot", label: "Didcot" },
  { value: "Dorchester", label: "Dorchester" },
  { value: "Faringdon", label: "Faringdon" },
  { value: "Henley on Thames", label: "Henley on Thames" },
  { value: "Neithrop", label: "Neithrop" },
  { value: "Oxford", label: "Oxford" },
  { value: "Ruscote", label: "Ruscote" },
  { value: "Thame", label: "Thame" },
  { value: "Wallingford", label: "Wallingford" },
  { value: "Wantage", label: "Wantage" },
  { value: "Watlington", label: "Watlington" },
  { value: "Weston Otmoor", label: "Weston Otmoor" },
  { value: "Witney", label: "Witney" },
  { value: "Woodstock", label: "Woodstock" },
  { value: "Oakham", label: "Oakham" },
  { value: "Uppingham", label: "Uppingham" },
  { value: "Bishop's Castle", label: "Bishop's Castle" },
  { value: "Bridgnorth", label: "Bridgnorth" },
  { value: "Broseley", label: "Broseley" },
  { value: "Church Stretton", label: "Church Stretton" },
  { value: "Cleobury Mortimer", label: "Cleobury Mortimer" },
  { value: "Clun", label: "Clun" },
  { value: "Craven Arms", label: "Craven Arms" },
  { value: "Dawley", label: "Dawley" },
  { value: "Ellesmere", label: "Ellesmere" },
  { value: "Ludlow", label: "Ludlow" },
  { value: "Madeley", label: "Madeley" },
  { value: "Market Drayton", label: "Market Drayton" },
  { value: "Much Wenlock", label: "Much Wenlock" },
  { value: "Newport", label: "Newport" },
  { value: "Oakengates", label: "Oakengates" },
  { value: "Oswestry", label: "Oswestry" },
  { value: "Shifnal", label: "Shifnal" },
  { value: "Shrewsbury", label: "Shrewsbury" },
  { value: "Telford", label: "Telford" },
  { value: "Wellington", label: "Wellington" },
  { value: "Wem", label: "Wem" },
  { value: "Whitchurch", label: "Whitchurch" },
  { value: "Axbridge", label: "Axbridge" },
  { value: "Bath", label: "Bath" },
  { value: "Bridgwater", label: "Bridgwater" },
  { value: "Bruton", label: "Bruton" },
  { value: "Burnham on Sea", label: "Burnham on Sea" },
  { value: "Castle Cary", label: "Castle Cary" },
  { value: "Chard", label: "Chard" },
  { value: "Clevedon", label: "Clevedon" },
  { value: "Crewkerne", label: "Crewkerne" },
  { value: "Dulverton", label: "Dulverton" },
  { value: "Frome", label: "Frome" },
  { value: "Glastonbury", label: "Glastonbury" },
  { value: "Highbridge", label: "Highbridge" },
  { value: "Ilminster", label: "Ilminster" },
  { value: "Keynsham", label: "Keynsham" },
  { value: "Langport", label: "Langport" },
  { value: "Midsomer Norton", label: "Midsomer Norton" },
  { value: "Minehead", label: "Minehead" },
  { value: "Nailsea", label: "Nailsea" },
  { value: "North Petherton", label: "North Petherton" },
  { value: "Norton Radstock", label: "Norton Radstock" },
  { value: "Portishead", label: "Portishead" },
  { value: "Portishead and North Weston", label: "Portishead and North Weston" },
  { value: "Radstock", label: "Radstock" },
  { value: "Shepton Mallet", label: "Shepton Mallet" },
  { value: "Somerton", label: "Somerton" },
  { value: "South Petherton", label: "South Petherton" },
  { value: "Street", label: "Street" },
  { value: "Taunton", label: "Taunton" },
  { value: "Watchet", label: "Watchet" },
  { value: "Wellington", label: "Wellington" },
  { value: "Wells", label: "Wells" },
  { value: "Weston super Mare", label: "Weston super Mare" },
  { value: "Wincanton", label: "Wincanton" },
  { value: "Winsford", label: "Winsford" },
  { value: "Wiveliscombe", label: "Wiveliscombe" },
  { value: "Yeovil", label: "Yeovil" },
  { value: "Anston", label: "Anston" },
  { value: "Askern", label: "Askern" },
  { value: "Barnsley", label: "Barnsley" },
  { value: "Bawtry", label: "Bawtry" },
  { value: "Brierley", label: "Brierley" },
  { value: "Conisbrough", label: "Conisbrough" },
  { value: "Dinnington", label: "Dinnington" },
  { value: "Doncaster", label: "Doncaster" },
  { value: "Edlington", label: "Edlington" },
  { value: "Hatfield", label: "Hatfield" },
  { value: "Hoyland", label: "Hoyland" },
  { value: "Maltby", label: "Maltby" },
  { value: "Mexborough", label: "Mexborough" },
  { value: "Penistone", label: "Penistone" },
  { value: "Rotherham", label: "Rotherham" },
  { value: "Sheffield", label: "Sheffield" },
  { value: "Stainforth", label: "Stainforth" },
  { value: "Stocksbridge", label: "Stocksbridge" },
  { value: "Swinton", label: "Swinton" },
  { value: "Thorne", label: "Thorne" },
  { value: "Tickhill", label: "Tickhill" },
  { value: "Wath upon Dearne", label: "Wath upon Dearne" },
  { value: "Wombwell", label: "Wombwell" },
  { value: "Alton", label: "Alton" },
  { value: "Biddulph", label: "Biddulph" },
  { value: "Burntwood", label: "Burntwood" },
  { value: "Burslem", label: "Burslem" },
  { value: "Burton upon Trent", label: "Burton upon Trent" },
  { value: "Cannock", label: "Cannock" },
  { value: "Cheadle", label: "Cheadle" },
  { value: "Eccleshall", label: "Eccleshall" },
  { value: "Fazeley", label: "Fazeley" },
  { value: "Fenton", label: "Fenton" },
  { value: "Hednesford", label: "Hednesford" },
  { value: "Kidsgrove", label: "Kidsgrove" },
  { value: "Leek", label: "Leek" },
  { value: "Lichfield", label: "Lichfield" },
  { value: "Longton", label: "Longton" },
  { value: "Newcastle under Lyme", label: "Newcastle under Lyme" },
  { value: "Penkridge", label: "Penkridge" },
  { value: "Perry Crofts", label: "Perry Crofts" },
  { value: "Rugeley", label: "Rugeley" },
  { value: "Stafford", label: "Stafford" },
  { value: "Stoke on Trent", label: "Stoke on Trent" },
  { value: "Stone", label: "Stone" },
  { value: "Tamworth", label: "Tamworth" },
  { value: "Tunstall", label: "Tunstall" },
  { value: "Uttoxeter", label: "Uttoxeter" },
  { value: "Aldeburgh", label: "Aldeburgh" },
  { value: "Beccles", label: "Beccles" },
  { value: "Brandon", label: "Brandon" },
  { value: "Bungay", label: "Bungay" },
  { value: "Bury St Edmunds", label: "Bury St Edmunds" },
  { value: "Carlton Colville", label: "Carlton Colville" },
  { value: "Clare", label: "Clare" },
  { value: "Dommoc", label: "Dommoc" },
  { value: "Dunwich", label: "Dunwich" },
  { value: "Eye", label: "Eye" },
  { value: "Felixstowe", label: "Felixstowe" },
  { value: "Framlingham", label: "Framlingham" },
  { value: "Hadleigh", label: "Hadleigh" },
  { value: "Halesworth", label: "Halesworth" },
  { value: "Haverhill", label: "Haverhill" },
  { value: "Ipswich", label: "Ipswich" },
  { value: "Kesgrave", label: "Kesgrave" },
  { value: "Leiston", label: "Leiston" },
  { value: "Lowestoft", label: "Lowestoft" },
  { value: "Mildenhall", label: "Mildenhall" },
  { value: "Needham Market", label: "Needham Market" },
  { value: "Newmarket", label: "Newmarket" },
  { value: "Orford", label: "Orford" },
  { value: "Otley", label: "Otley" },
  { value: "Saxmundham", label: "Saxmundham" },
  { value: "Southwold", label: "Southwold" },
  { value: "Stowmarket", label: "Stowmarket" },
  { value: "Sudbury", label: "Sudbury" },
  { value: "Woodbridge", label: "Woodbridge" },
  { value: "Ashford", label: "Ashford" },
  { value: "Beltchingley", label: "Beltchingley" },
  { value: "Camberley", label: "Camberley" },
  { value: "Chertsey", label: "Chertsey" },
  { value: "Croydon", label: "Croydon" },
  { value: "Dorking", label: "Dorking" },
  { value: "Egham", label: "Egham" },
  { value: "Epsom", label: "Epsom" },
  { value: "Esher", label: "Esher" },
  { value: "Farnham", label: "Farnham" },
  { value: "Godalming", label: "Godalming" },
  { value: "Gomshall", label: "Gomshall" },
  { value: "Gratton", label: "Gratton" },
  { value: "Great Brookham", label: "Great Brookham" },
  { value: "Guildford", label: "Guildford" },
  { value: "Haslemere", label: "Haslemere" },
  { value: "Horley", label: "Horley" },
  { value: "Kingston upon Thames", label: "Kingston upon Thames" },
  { value: "Leatherhead", label: "Leatherhead" },
  { value: "Redhill", label: "Redhill" },
  { value: "Reigate", label: "Reigate" },
  { value: "Southwark", label: "Southwark" },
  { value: "Staines upon Thames", label: "Staines upon Thames" },
  { value: "Walton on Thames", label: "Walton on Thames" },
  { value: "Weybridge", label: "Weybridge" },
  { value: "Woking", label: "Woking" },
  { value: "Birtley", label: "Birtley" },
  { value: "Blaydon on tyne", label: "Blaydon on tyne" },
  { value: "Cullercoats", label: "Cullercoats" },
  { value: "Darsley Park", label: "Darsley Park" },
  { value: "Dunston", label: "Dunston" },
  { value: "Gateshead", label: "Gateshead" },
  { value: "Hetton", label: "Hetton" },
  { value: "Houghton le Spring", label: "Houghton le Spring" },
  { value: "Howdon", label: "Howdon" },
  { value: "Jarrow", label: "Jarrow" },
  { value: "Killingworth", label: "Killingworth" },
  { value: "Little Benton", label: "Little Benton" },
  { value: "Longbenton", label: "Longbenton" },
  { value: "Low Fell", label: "Low Fell" },
  { value: "Newcastle upon Tyne", label: "Newcastle upon Tyne" },
  { value: "North Shields", label: "North Shields" },
  { value: "Ryton", label: "Ryton" },
  { value: "Sheriff Hill", label: "Sheriff Hill" },
  { value: "South Shields", label: "South Shields" },
  { value: "Sunderland", label: "Sunderland" },
  { value: "Tynemouth", label: "Tynemouth" },
  { value: "Wallsend", label: "Wallsend" },
  { value: "Washington", label: "Washington" },
  { value: "Whitley Bay", label: "Whitley Bay" },
  { value: "Willington Quay", label: "Willington Quay" },
  { value: "Windy Nook", label: "Windy Nook" },
  { value: "Alcester", label: "Alcester" },
  { value: "Atherstone", label: "Atherstone" },
  { value: "Bedworth", label: "Bedworth" },
  { value: "Coleshill", label: "Coleshill" },
  { value: "Henley in Arden", label: "Henley in Arden" },
  { value: "Kenilworth", label: "Kenilworth" },
  { value: "Middle Quinton", label: "Middle Quinton" },
  { value: "Nuneaton", label: "Nuneaton" },
  { value: "Royal Leamington Spa", label: "Royal Leamington Spa" },
  { value: "Rugby", label: "Rugby" },
  { value: "Shipston on Stour", label: "Shipston on Stour" },
  { value: "Southam", label: "Southam" },
  { value: "Stratford upon Avon", label: "Stratford upon Avon" },
  { value: "Warwick", label: "Warwick" },
  { value: "Whitnash", label: "Whitnash" },
  { value: "Aldridge", label: "Aldridge" },
  { value: "Bilston", label: "Bilston" },
  { value: "Birmingham", label: "Birmingham" },
  { value: "Blackheath", label: "Blackheath" },
  { value: "Bloxwich", label: "Bloxwich" },
  { value: "Brierley Hill", label: "Brierley Hill" },
  { value: "Brownhills", label: "Brownhills" },
  { value: "Coal Pool", label: "Coal Pool" },
  { value: "Coseley", label: "Coseley" },
  { value: "Coventry", label: "Coventry" },
  { value: "Cradley Heath", label: "Cradley Heath" },
  { value: "Darlaston", label: "Darlaston" },
  { value: "Dudley", label: "Dudley" },
  { value: "Fordbridge", label: "Fordbridge" },
  { value: "Gornal", label: "Gornal" },
  { value: "Halesowen", label: "Halesowen" },
  { value: "Lye", label: "Lye" },
  { value: "Moxley", label: "Moxley" },
  { value: "Netherton", label: "Netherton" },
  { value: "Oldbury", label: "Oldbury" },
  { value: "Pelsall", label: "Pelsall" },
  { value: "Rowley Regis", label: "Rowley Regis" },
  { value: "Sedgley", label: "Sedgley" },
  { value: "Smethwick", label: "Smethwick" },
  { value: "Solihull", label: "Solihull" },
  { value: "Stourbridge", label: "Stourbridge" },
  { value: "Sutton Coldfield", label: "Sutton Coldfield" },
  { value: "Tipton", label: "Tipton" },
  { value: "Walsall", label: "Walsall" },
  { value: "Wednesbury", label: "Wednesbury" },
  { value: "Wednesfield", label: "Wednesfield" },
  { value: "West Bromwich", label: "West Bromwich" },
  { value: "Willenhall", label: "Willenhall" },
  { value: "Wolverhampton", label: "Wolverhampton" },
  { value: "Arundel", label: "Arundel" },
  { value: "Bognor Regis", label: "Bognor Regis" },
  { value: "Burgess Hill", label: "Burgess Hill" },
  { value: "Chichester", label: "Chichester" },
  { value: "Crawley", label: "Crawley" },
  { value: "Cuckfield", label: "Cuckfield" },
  { value: "East Grinstead", label: "East Grinstead" },
  { value: "Haywards Heath", label: "Haywards Heath" },
  { value: "Horsham", label: "Horsham" },
  { value: "Littlehampton", label: "Littlehampton" },
  { value: "Midhurst", label: "Midhurst" },
  { value: "Petworth", label: "Petworth" },
  { value: "Selsey", label: "Selsey" },
  { value: "Shoreham by Sea", label: "Shoreham by Sea" },
  { value: "Southwick", label: "Southwick" },
  { value: "Steyning", label: "Steyning" },
  { value: "Worthing", label: "Worthing" },
  { value: "Baildon", label: "Baildon" },
  { value: "Batley", label: "Batley" },
  { value: "Bingley", label: "Bingley" },
  { value: "Bradford", label: "Bradford" },
  { value: "Brighouse", label: "Brighouse" },
  { value: "Castleford", label: "Castleford" },
  { value: "Cleckheaton", label: "Cleckheaton" },
  { value: "Denholme", label: "Denholme" },
  { value: "Dewsbury", label: "Dewsbury" },
  { value: "Elland", label: "Elland" },
  { value: "Farsley", label: "Farsley" },
  { value: "Featherstone", label: "Featherstone" },
  { value: "Garforth", label: "Garforth" },
  { value: "Guiseley", label: "Guiseley" },
  { value: "Halifax", label: "Halifax" },
  { value: "Hebden Bridge", label: "Hebden Bridge" },
  { value: "Hebden Royd", label: "Hebden Royd" },
  { value: "Heckmondwike", label: "Heckmondwike" },
  { value: "Hemsworth", label: "Hemsworth" },
  { value: "Holmfirth", label: "Holmfirth" },
  { value: "Horsforth", label: "Horsforth" },
  { value: "Huddersfield", label: "Huddersfield" },
  { value: "Ilkley", label: "Ilkley" },
  { value: "Keighley", label: "Keighley" },
  { value: "Knottingley", label: "Knottingley" },
  { value: "Leeds", label: "Leeds" },
  { value: "Meltham", label: "Meltham" },
  { value: "Mirfield", label: "Mirfield" },
  { value: "Morley", label: "Morley" },
  { value: "Mytholmroyd", label: "Mytholmroyd" },
  { value: "Normanton", label: "Normanton" },
  { value: "Ossett", label: "Ossett" },
  { value: "Otley", label: "Otley" },
  { value: "Pontefract", label: "Pontefract" },
  { value: "Pudsey", label: "Pudsey" },
  { value: "Rothwell", label: "Rothwell" },
  { value: "Shipley", label: "Shipley" },
  { value: "Silsden", label: "Silsden" },
  { value: "South Elmsall", label: "South Elmsall" },
  { value: "South Kirkby and Moorthorpe", label: "South Kirkby and Moorthorpe" },
  { value: "Sowerby Bridge", label: "Sowerby Bridge" },
  { value: "Todmorden", label: "Todmorden" },
  { value: "Wakefield", label: "Wakefield" },
  { value: "Wetherby", label: "Wetherby" },
  { value: "Yeadon", label: "Yeadon" },
  { value: "Amesbury", label: "Amesbury" },
  { value: "Bradford on Avon", label: "Bradford on Avon" },
  { value: "Calne", label: "Calne" },
  { value: "Chippenham", label: "Chippenham" },
  { value: "Corsham", label: "Corsham" },
  { value: "Cricklade", label: "Cricklade" },
  { value: "Devizes", label: "Devizes" },
  { value: "Highworth", label: "Highworth" },
  { value: "Ludgershall", label: "Ludgershall" },
  { value: "Malmesbury", label: "Malmesbury" },
  { value: "Marlborough", label: "Marlborough" },
  { value: "Melksham", label: "Melksham" },
  { value: "Mere", label: "Mere" },
  { value: "Royal Wootton Bassett", label: "Royal Wootton Bassett" },
  { value: "Salisbury", label: "Salisbury" },
  { value: "Swindon", label: "Swindon" },
  { value: "Tidworth", label: "Tidworth" },
  { value: "Tisbury", label: "Tisbury" },
  { value: "Trowbridge", label: "Trowbridge" },
  { value: "Warminster", label: "Warminster" },
  { value: "Westbury", label: "Westbury" },
  { value: "Wilton", label: "Wilton" },
  { value: "Bewdley", label: "Bewdley" },
  { value: "Bromsgrove", label: "Bromsgrove" },
  { value: "Droitwich Spa", label: "Droitwich Spa" },
  { value: "Evesham", label: "Evesham" },
  { value: "Great Malvern", label: "Great Malvern" },
  { value: "Kidderminster", label: "Kidderminster" },
  { value: "Malvern", label: "Malvern" },
  { value: "Pershore", label: "Pershore" },
  { value: "Redditch", label: "Redditch" },
  { value: "Stourport on Severn", label: "Stourport on Severn" },
  { value: "Tenbury Wells", label: "Tenbury Wells" },
  { value: "Upton upon Severn", label: "Upton upon Severn" },
  { value: "Worcester", label: "Worcester" },
  { value: "Antrim", label: "Antrim" },
  { value: "Ballycastle", label: "Ballycastle" },
  { value: "Ballyclare", label: "Ballyclare" },
  { value: "Ballymena", label: "Ballymena" },
  { value: "Ballymoney", label: "Ballymoney" },
  { value: "Bushmills", label: "Bushmills" },
  { value: "Carrickfergus", label: "Carrickfergus" },
  { value: "Crumlin", label: "Crumlin" },
  { value: "Greenisland", label: "Greenisland" },
  { value: "Larne", label: "Larne" },
  { value: "Lisburn", label: "Lisburn" },
  { value: "Merville Garden Village", label: "Merville Garden Village" },
  { value: "Newtownabbey", label: "Newtownabbey" },
  { value: "Portrush", label: "Portrush" },
  { value: "Randalstown", label: "Randalstown" },
  { value: "Armagh", label: "Armagh" },
  { value: "Craigavon", label: "Craigavon" },
  { value: "Lurgan", label: "Lurgan" },
  { value: "Markethill", label: "Markethill" },
  { value: "Newry", label: "Newry" },
  { value: "Portadown", label: "Portadown" },
  { value: "Ballynahinch", label: "Ballynahinch" },
  { value: "Banbridge", label: "Banbridge" },
  { value: "Bangor", label: "Bangor" },
  { value: "Carryduff", label: "Carryduff" },
  { value: "Castlewellan", label: "Castlewellan" },
  { value: "Comber", label: "Comber" },
  { value: "Donaghadee", label: "Donaghadee" },
  { value: "Doromore", label: "Doromore" },
  { value: "Downpatrick", label: "Downpatrick" },
  { value: "Dundonald", label: "Dundonald" },
  { value: "Holywood", label: "Holywood" },
  { value: "Kilkeel", label: "Kilkeel" },
  { value: "Killyleagh", label: "Killyleagh" },
  { value: "Lisburn", label: "Lisburn" },
  { value: "Newcastle", label: "Newcastle" },
  { value: "Newtownards", label: "Newtownards" },
  { value: "Portaferry", label: "Portaferry" },
  { value: "Rostrevor", label: "Rostrevor" },
  { value: "Saintfield", label: "Saintfield" },
  { value: "Warrenpoint", label: "Warrenpoint" },
  { value: "Enniskillen", label: "Enniskillen" },
  { value: "Lisnaskea", label: "Lisnaskea" },
  { value: "Coleraine", label: "Coleraine" },
  { value: "Derry", label: "Derry" },
  { value: "Limavady", label: "Limavady" },
  { value: "Magherafelt", label: "Magherafelt" },
  { value: "Portstewart", label: "Portstewart" },
  { value: "Castlederg", label: "Castlederg" },
  { value: "Clogher", label: "Clogher" },
  { value: "Coalisland", label: "Coalisland" },
  { value: "Cookstown", label: "Cookstown" },
  { value: "Dungannon", label: "Dungannon" },
  { value: "Fintona", label: "Fintona" },
  { value: "Fivemiletown", label: "Fivemiletown" },
  { value: "Omagh", label: "Omagh" },
  { value: "Strabane", label: "Strabane" },
  { value: "Aberdeen", label: "Aberdeen" },
  { value: "Alford", label: "Alford" },
  { value: "Ballater", label: "Ballater" },
  { value: "Banchory", label: "Banchory" },
  { value: "Banff", label: "Banff" },
  { value: "Banff and Macduff", label: "Banff and Macduff" },
  { value: "Blackburn", label: "Blackburn" },
  { value: "Boddam", label: "Boddam" },
  { value: "Clerkhill", label: "Clerkhill" },
  { value: "Ellon", label: "Ellon" },
  { value: "Fraserburgh", label: "Fraserburgh" },
  { value: "Huntly", label: "Huntly" },
  { value: "Insch", label: "Insch" },
  { value: "Inverbervie", label: "Inverbervie" },
  { value: "Inverurie", label: "Inverurie" },
  { value: "Kemnay", label: "Kemnay" },
  { value: "Kintore", label: "Kintore" },
  { value: "Laurencekirk", label: "Laurencekirk" },
  { value: "Macduff", label: "Macduff" },
  { value: "Maud", label: "Maud" },
  { value: "Oldmeldrum", label: "Oldmeldrum" },
  { value: "Peterhead", label: "Peterhead" },
  { value: "Portlethen", label: "Portlethen" },
  { value: "Portsoy", label: "Portsoy" },
  { value: "Red Cloak", label: "Red Cloak" },
  { value: "Rosehearty", label: "Rosehearty" },
  { value: "Stonehaven", label: "Stonehaven" },
  { value: "Turriff", label: "Turriff" },
  { value: "Westhill", label: "Westhill" },
  { value: "Arbroath", label: "Arbroath" },
  { value: "Brechin", label: "Brechin" },
  { value: "Carnoustie", label: "Carnoustie" },
  { value: "Forfar", label: "Forfar" },
  { value: "Kirriemuir", label: "Kirriemuir" },
  { value: "Monifieth", label: "Monifieth" },
  { value: "Montrose", label: "Montrose" },
  { value: "Alloa", label: "Alloa" },
  { value: "Alva", label: "Alva" },
  { value: "Clackmannan", label: "Clackmannan" },
  { value: "Dollar", label: "Dollar" },
  { value: "Menstrie", label: "Menstrie" },
  { value: "Tillicoultry", label: "Tillicoultry" },
  { value: "Tullibody", label: "Tullibody" },
  { value: "Annan", label: "Annan" },
  { value: "Castle Douglas", label: "Castle Douglas" },
  { value: "Dalbeattie", label: "Dalbeattie" },
  { value: "Dumfries", label: "Dumfries" },
  { value: "Gatehouse of Fleet", label: "Gatehouse of Fleet" },
  { value: "Gretna", label: "Gretna" },
  { value: "Kelloholm", label: "Kelloholm" },
  { value: "Kirkconnel", label: "Kirkconnel" },
  { value: "Kirkcudbright", label: "Kirkcudbright" },
  { value: "Langholm", label: "Langholm" },
  { value: "Lochmaben", label: "Lochmaben" },
  { value: "Lockerbie", label: "Lockerbie" },
  { value: "Moffat", label: "Moffat" },
  { value: "Monreith", label: "Monreith" },
  { value: "Newbridge Drive", label: "Newbridge Drive" },
  { value: "Newton Stewart", label: "Newton Stewart" },
  { value: "Sanquhar", label: "Sanquhar" },
  { value: "Stranraer", label: "Stranraer" },
  { value: "Thornhill", label: "Thornhill" },
  { value: "Wigtown", label: "Wigtown" },
  { value: "Dundee", label: "Dundee" },
  { value: "Cockenzie and Port Seton", label: "Cockenzie and Port Seton" },
  { value: "Dunbar", label: "Dunbar" },
  { value: "Haddington", label: "Haddington" },
  { value: "Musselburgh", label: "Musselburgh" },
  { value: "North Berwick", label: "North Berwick" },
  { value: "Prestonpans", label: "Prestonpans" },
  { value: "Tranent", label: "Tranent" },
  { value: "Edinburgh?", label: "Edinburgh?" },
  { value: "Airth", label: "Airth" },
  { value: "Bo'ness", label: "Bo'ness" },
  { value: "Bonnybridge", label: "Bonnybridge" },
  { value: "Borrowstounness", label: "Borrowstounness" },
  { value: "Carron", label: "Carron" },
  { value: "Denny", label: "Denny" },
  { value: "Duniplace", label: "Duniplace" },
  { value: "Dunmore", label: "Dunmore" },
  { value: "Falkirk", label: "Falkirk" },
  { value: "Grahamston", label: "Grahamston" },
  { value: "Grangemouth", label: "Grangemouth" },
  { value: "Larbert", label: "Larbert" },
  { value: "Stenhousemuir", label: "Stenhousemuir" },
  { value: "Anstruther", label: "Anstruther" },
  { value: "Auchtermuchty", label: "Auchtermuchty" },
  { value: "Balcurvie", label: "Balcurvie" },
  { value: "Ballingry", label: "Ballingry" },
  { value: "Benarty", label: "Benarty" },
  { value: "Buckhaven", label: "Buckhaven" },
  { value: "Burntisland", label: "Burntisland" },
  { value: "Collydean", label: "Collydean" },
  { value: "Cowdenbeath", label: "Cowdenbeath" },
  { value: "Crail", label: "Crail" },
  { value: "Cupar", label: "Cupar" },
  { value: "Dalgety Bay", label: "Dalgety Bay" },
  { value: "Dunfermline", label: "Dunfermline" },
  { value: "Dysart", label: "Dysart" },
  { value: "East Wemyss", label: "East Wemyss" },
  { value: "Falkland", label: "Falkland" },
  { value: "Glenrothes", label: "Glenrothes" },
  { value: "Inverkeithing", label: "Inverkeithing" },
  { value: "Kelty", label: "Kelty" },
  { value: "Kincardine", label: "Kincardine" },
  { value: "Kinghorn", label: "Kinghorn" },
  { value: "Kinglassie", label: "Kinglassie" },
  { value: "Kirkcaldy", label: "Kirkcaldy" },
  { value: "Ladybank", label: "Ladybank" },
  { value: "Letham", label: "Letham" },
  { value: "Leuchars", label: "Leuchars" },
  { value: "Leven", label: "Leven" },
  { value: "Levenmouth", label: "Levenmouth" },
  { value: "Lochgelly", label: "Lochgelly" },
  { value: "Markinch", label: "Markinch" },
  { value: "Methil", label: "Methil" },
  { value: "Newburgh", label: "Newburgh" },
  { value: "Newport on Tay", label: "Newport on Tay" },
  { value: "North Queensferry", label: "North Queensferry" },
  { value: "Pitcoudie", label: "Pitcoudie" },
  { value: "Pittenweem", label: "Pittenweem" },
  { value: "Rosyth", label: "Rosyth" },
  { value: "St Andrews", label: "St Andrews" },
  { value: "St Monans", label: "St Monans" },
  { value: "Tayport", label: "Tayport" },
  { value: "Woodhaven", label: "Woodhaven" },
  { value: "Wormit", label: "Wormit" },
  { value: "Alness", label: "Alness" },
  { value: "Aviemore", label: "Aviemore" },
  { value: "Brora", label: "Brora" },
  { value: "Cromarty", label: "Cromarty" },
  { value: "Dingwall", label: "Dingwall" },
  { value: "Dornoch", label: "Dornoch" },
  { value: "Fort William", label: "Fort William" },
  { value: "Fortrose", label: "Fortrose" },
  { value: "Grantown on Spey", label: "Grantown on Spey" },
  { value: "Invergordon", label: "Invergordon" },
  { value: "Inverlochy", label: "Inverlochy" },
  { value: "Inverness", label: "Inverness" },
  { value: "Kingussie", label: "Kingussie" },
  { value: "Mallaig", label: "Mallaig" },
  { value: "Nairn", label: "Nairn" },
  { value: "Portree", label: "Portree" },
  { value: "Tain", label: "Tain" },
  { value: "Thurso", label: "Thurso" },
  { value: "Ullapool", label: "Ullapool" },
  { value: "Wick", label: "Wick" },
  { value: "Bathgate", label: "Bathgate" },
  { value: "Dalkeith", label: "Dalkeith" },
  { value: "Dunbar", label: "Dunbar" },
  { value: "Edinburgh", label: "Edinburgh" },
  { value: "Haddington", label: "Haddington" },
  { value: "Linlithgow", label: "Linlithgow" },
  { value: "Loanhead", label: "Loanhead" },
  { value: "Musselburgh", label: "Musselburgh" },
  { value: "North Berwick", label: "North Berwick" },
  { value: "Penicuik", label: "Penicuik" },
  { value: "Buckie", label: "Buckie" },
  { value: "Cullen", label: "Cullen" },
  { value: "Dufftown", label: "Dufftown" },
  { value: "Elgin", label: "Elgin" },
  { value: "Forres", label: "Forres" },
  { value: "Keith", label: "Keith" },
  { value: "Lossiemouth", label: "Lossiemouth" },
  { value: "Aberfeldy", label: "Aberfeldy" },
  { value: "Auchterarder", label: "Auchterarder" },
  { value: "Birnam", label: "Birnam" },
  { value: "Blackford", label: "Blackford" },
  { value: "Blair Atholl", label: "Blair Atholl" },
  { value: "Blairgowrie and Rattray", label: "Blairgowrie and Rattray" },
  { value: "Bridge of Earn", label: "Bridge of Earn" },
  { value: "Bridge of Tilt", label: "Bridge of Tilt" },
  { value: "Comrie", label: "Comrie" },
  { value: "Coupar Angus", label: "Coupar Angus" },
  { value: "Crieff", label: "Crieff" },
  { value: "Kinross", label: "Kinross" },
  { value: "Perth", label: "Perth" },
  { value: "Pitlochry", label: "Pitlochry" },
  { value: "Scone", label: "Scone" },
  { value: "Coldstream", label: "Coldstream" },
  { value: "Duns", label: "Duns" },
  { value: "Earlston", label: "Earlston" },
  { value: "Eyemouth", label: "Eyemouth" },
  { value: "Galashiels", label: "Galashiels" },
  { value: "Greenlaw", label: "Greenlaw" },
  { value: "Hawick", label: "Hawick" },
  { value: "Innerleithen", label: "Innerleithen" },
  { value: "Jedburgh", label: "Jedburgh" },
  { value: "Kelso", label: "Kelso" },
  { value: "Lauder", label: "Lauder" },
  { value: "Melrose", label: "Melrose" },
  { value: "Newtown St Boswells", label: "Newtown St Boswells" },
  { value: "Peebles", label: "Peebles" },
  { value: "Selkirk", label: "Selkirk" },
  { value: "Bridge of Allan", label: "Bridge of Allan" },
  { value: "Callander", label: "Callander" },
  { value: "Doune", label: "Doune" },
  { value: "Dunblane", label: "Dunblane" },
  { value: "Stirling", label: "Stirling" },
  { value: "Airdrie", label: "Airdrie" },
  { value: "Ayr", label: "Ayr" },
  { value: "Barrhead", label: "Barrhead" },
  { value: "Bearsden", label: "Bearsden" },
  { value: "Bellshill", label: "Bellshill" },
  { value: "Biggar", label: "Biggar" },
  { value: "Campbeltown", label: "Campbeltown" },
  { value: "Carluke", label: "Carluke" },
  { value: "Clydebank", label: "Clydebank" },
  { value: "Coatbridge", label: "Coatbridge" },
  { value: "Cumbernauld", label: "Cumbernauld" },
  { value: "Dumbarton", label: "Dumbarton" },
  { value: "Dunoon", label: "Dunoon" },
  { value: "East Kilbride", label: "East Kilbride" },
  { value: "Glasgow", label: "Glasgow" },
  { value: "Gourock", label: "Gourock" },
  { value: "Greenock", label: "Greenock" },
  { value: "Hamilton", label: "Hamilton" },
  { value: "Helensburgh", label: "Helensburgh" },
  { value: "Inveraray", label: "Inveraray" },
  { value: "Irvine", label: "Irvine" },
  { value: "Johnstone", label: "Johnstone" },
  { value: "Kilbarchan", label: "Kilbarchan" },
  { value: "Kilmarnock", label: "Kilmarnock" },
  { value: "Kilwinning", label: "Kilwinning" },
  { value: "Lanark", label: "Lanark" },
  { value: "Largs", label: "Largs" },
  { value: "Lochgilphead", label: "Lochgilphead" },
  { value: "Maybole", label: "Maybole" },
  { value: "Milngavie", label: "Milngavie" },
  { value: "Motherwell", label: "Motherwell" },
  { value: "Oban", label: "Oban" },
  { value: "Paisley", label: "Paisley" },
  { value: "Prestwick", label: "Prestwick" },
  { value: "Rothesay", label: "Rothesay" },
  { value: "Rutherglen", label: "Rutherglen" },
  { value: "Saltcoats", label: "Saltcoats" },
  { value: "Tobermory", label: "Tobermory" },
  { value: "Troon", label: "Troon" },
  { value: "Armadale", label: "Armadale" },
  { value: "Ballencrieff", label: "Ballencrieff" },
  { value: "Bathgate", label: "Bathgate" },
  { value: "Blackburn", label: "Blackburn" },
  { value: "Blackridge", label: "Blackridge" },
  { value: "Bridgend", label: "Bridgend" },
  { value: "Broxburn", label: "Broxburn" },
  { value: "East Calder", label: "East Calder" },
  { value: "Linlithgow", label: "Linlithgow" },
  { value: "Livingston", label: "Livingston" },
  { value: "Stoneyburn", label: "Stoneyburn" },
  { value: "Whitburn", label: "Whitburn" },
  { value: "Kirkwall", label: "Kirkwall" },
  { value: "Lerwick", label: "Lerwick" },
  { value: "Stornoway", label: "Stornoway" },
  { value: "Amlwch", label: "Amlwch" },
  { value: "Beaumaris", label: "Beaumaris" },
  { value: "Benllech", label: "Benllech" },
  { value: "Holyhead", label: "Holyhead" },
  { value: "Llanfairpwllgwyngyll", label: "Llanfairpwllgwyngyll" },
  { value: "Llangefni", label: "Llangefni" },
  { value: "Menai Bridge", label: "Menai Bridge" },
  { value: "Ammanford", label: "Ammanford" },
  { value: "Burry Port", label: "Burry Port" },
  { value: "Carmarthen", label: "Carmarthen" },
  { value: "Garnant", label: "Garnant" },
  { value: "Glanamman", label: "Glanamman" },
  { value: "Kidwelly", label: "Kidwelly" },
  { value: "Laugharne", label: "Laugharne" },
  { value: "Llandeilo", label: "Llandeilo" },
  { value: "Llandovery", label: "Llandovery" },
  { value: "Llanelli", label: "Llanelli" },
  { value: "Newcastle Emlyn", label: "Newcastle Emlyn" },
  { value: "St Clears", label: "St Clears" },
  { value: "Whitland", label: "Whitland" },
  { value: "Aberaeron", label: "Aberaeron" },
  { value: "Aberystwyth", label: "Aberystwyth" },
  { value: "Cardigan", label: "Cardigan" },
  { value: "Lampeter", label: "Lampeter" },
  { value: "Llandysul", label: "Llandysul" },
  { value: "New Quay", label: "New Quay" },
  { value: "Tregaron", label: "Tregaron" },
  { value: "Abergele", label: "Abergele" },
  { value: "Colwyn Bay", label: "Colwyn Bay" },
  { value: "Conwy", label: "Conwy" },
  { value: "Deganwy", label: "Deganwy" },
  { value: "Llandudno", label: "Llandudno" },
  { value: "Llandudno Junction", label: "Llandudno Junction" },
  { value: "Llanfairfechan", label: "Llanfairfechan" },
  { value: "Llanrwst", label: "Llanrwst" },
  { value: "Old Colwyn", label: "Old Colwyn" },
  { value: "Penmaenmawr", label: "Penmaenmawr" },
  { value: "Towyn", label: "Towyn" },
  { value: "Carrog", label: "Carrog" },
  { value: "Corwen", label: "Corwen" },
  { value: "Denbigh", label: "Denbigh" },
  { value: "Gellifor", label: "Gellifor" },
  { value: "Llangollen", label: "Llangollen" },
  { value: "Prestatyn", label: "Prestatyn" },
  { value: "Rhuddlan", label: "Rhuddlan" },
  { value: "Rhyl", label: "Rhyl" },
  { value: "Ruthin", label: "Ruthin" },
  { value: "St Asaph", label: "St Asaph" },
  { value: "Bagallit", label: "Bagallit" },
  { value: "Broughton", label: "Broughton" },
  { value: "Buckley", label: "Buckley" },
  { value: "Caerwys", label: "Caerwys" },
  { value: "Connah's Quay", label: "Connah's Quay" },
  { value: "Ewole", label: "Ewole" },
  { value: "Flint", label: "Flint" },
  { value: "Hawarden", label: "Hawarden" },
  { value: "Holywell", label: "Holywell" },
  { value: "Mold", label: "Mold" },
  { value: "Queensferry", label: "Queensferry" },
  { value: "Saltney", label: "Saltney" },
  { value: "Shotton", label: "Shotton" },
  { value: "Abertillery", label: "Abertillery" },
  { value: "Blaina", label: "Blaina" },
  { value: "Brynmawr", label: "Brynmawr" },
  { value: "Cwmbran", label: "Cwmbran" },
  { value: "Ebbw Vale", label: "Ebbw Vale" },
  { value: "Newport", label: "Newport" },
  { value: "Tafarnaubach", label: "Tafarnaubach" },
  { value: "Tredegar", label: "Tredegar" },
  { value: "Bala", label: "Bala" },
  { value: "Bangor", label: "Bangor" },
  { value: "Barmouth", label: "Barmouth" },
  { value: "Beaumaris", label: "Beaumaris" },
  { value: "Betws y Coed", label: "Betws y Coed" },
  { value: "Blaenau Ffestiniog", label: "Blaenau Ffestiniog" },
  { value: "Caernarfon", label: "Caernarfon" },
  { value: "Conwy", label: "Conwy" },
  { value: "Criccieth", label: "Criccieth" },
  { value: "Dolgellau", label: "Dolgellau" },
  { value: "Ffestiniog", label: "Ffestiniog" },
  { value: "Harlech", label: "Harlech" },
  { value: "Holyhead", label: "Holyhead" },
  { value: "Llanberis", label: "Llanberis" },
  { value: "Llanfachreth", label: "Llanfachreth" },
  { value: "Nefyn", label: "Nefyn" },
  { value: "Porthmadog", label: "Porthmadog" },
  { value: "Pwllheli", label: "Pwllheli" },
  { value: "Tywyn", label: "Tywyn" },
  { value: "Y Felinheli", label: "Y Felinheli" },
  { value: "Aberdare", label: "Aberdare" },
  { value: "Bridgend", label: "Bridgend" },
  { value: "Caerphilly", label: "Caerphilly" },
  { value: "Llantrisant", label: "Llantrisant" },
  { value: "Maesteg", label: "Maesteg" },
  { value: "Merthyr Tydfil", label: "Merthyr Tydfil" },
  { value: "Pontypridd", label: "Pontypridd" },
  { value: "Porth", label: "Porth" },
  { value: "Porthcawl", label: "Porthcawl" },
  { value: "Abergavenny", label: "Abergavenny" },
  { value: "Caldicot", label: "Caldicot" },
  { value: "Chepstow", label: "Chepstow" },
  { value: "Monmouth", label: "Monmouth" },
  { value: "Usk", label: "Usk" },
  { value: "Fishguard", label: "Fishguard" },
  { value: "Goodwick", label: "Goodwick" },
  { value: "Hakin", label: "Hakin" },
  { value: "Haverfordwest", label: "Haverfordwest" },
  { value: "Milford Haven", label: "Milford Haven" },
  { value: "Narberth", label: "Narberth" },
  { value: "Newport", label: "Newport" },
  { value: "Neyland", label: "Neyland" },
  { value: "Pembroke", label: "Pembroke" },
  { value: "Pembroke Dock", label: "Pembroke Dock" },
  { value: "St Davids", label: "St Davids" },
  { value: "Tenby", label: "Tenby" },
  { value: "Brecon", label: "Brecon" },
  { value: "Builth Wells", label: "Builth Wells" },
  { value: "Cefnllys", label: "Cefnllys" },
  { value: "Crickhowell", label: "Crickhowell" },
  { value: "Hay on Wye", label: "Hay on Wye" },
  { value: "Knighton", label: "Knighton" },
  { value: "Llandrindod Wells", label: "Llandrindod Wells" },
  { value: "Llanfair Caereinion", label: "Llanfair Caereinion" },
  { value: "Llanfyllin", label: "Llanfyllin" },
  { value: "Llangors", label: "Llangors" },
  { value: "Llanidloes", label: "Llanidloes" },
  { value: "Llanwrtyd Wells", label: "Llanwrtyd Wells" },
  { value: "Machynlleth", label: "Machynlleth" },
  { value: "Montgomery", label: "Montgomery" },
  { value: "Newtown", label: "Newtown" },
  { value: "Old Radnor", label: "Old Radnor" },
  { value: "Presteigne", label: "Presteigne" },
  { value: "Rhayader", label: "Rhayader" },
  { value: "Talgarth", label: "Talgarth" },
  { value: "Welshpool", label: "Welshpool" },
  { value: "Barry", label: "Barry" },
  { value: "Cardiff", label: "Cardiff" },
  { value: "Cowbridge", label: "Cowbridge" },
  { value: "Llantwit Major", label: "Llantwit Major" },
  { value: "Penarth", label: "Penarth" },
  { value: "Gorseinon", label: "Gorseinon" },
  { value: "Lliw Valey", label: "Lliw Valey" },
  { value: "Neath", label: "Neath" },
  { value: "Port Talbot", label: "Port Talbot" },
  { value: "Swansea", label: "Swansea" },
  { value: "Chirk", label: "Chirk" },
  { value: "Overton on Dee", label: "Overton on Dee" },
  { value: "Rhosllannerchrugog", label: "Rhosllannerchrugog" },
  { value: "Rhosnesni", label: "Rhosnesni" },
  { value: "Wrexham", label: "Wrexham" },
]